### ISSUE TITLE
Support .js with allowJs?

### ISSUE THREAD

**Issue by cspotcode** [stringham/copy-with-imports#2]
Is it possible to support `.js` files with `allowJs`?

I imagine the changes would include:

- file extension filters check tsconfig for allowJs.  If true, match against `.js` and `.jsx`
- check for a "jsconfig.json" if "tsconfig.json" is missing

**Comment by stringham** [comment]
yeah, it seems like this would be reasonable. I don't have any projects that use allowJs, but if you want to open a PR I'd be happy to accept it.

**Comment by stringham** [comment]
It would be really easy to handle copying and pasting between two .js files with relative paths. I'll push that change this morning.

What would we use the jsconfig for?

**Comment by stringham** [comment]
For `.js` files, we would need to handle imports that look like:

```js
const foo = require('./foo');
```

right?

**Comment by cspotcode** [comment]
Oh I don't know, I was assuming we'd limit ourselves to whatever
TypeScript's language service recognizes as an import statement.  I'm not
sure if it's more flexible in allowJs mode; I've never actually used it
myself.

**Comment by stringham** [comment]
I pushed a change today that works for es6 style imports/exports in javascript.

If we want to handle statements like `const foo = require('./foo');` it will take additional work.

**Comment by cspotcode** [comment]
Oh awesome!  That was fast.
