### ISSUE TITLE
Copying code messes up redo

### ISSUE THREAD

**Issue by cafesanu** [stringham/copy-with-imports#4]
let's say you do undo (cmd+z) a couple of times, then copy something(cmd+c), and then redo (cmd+shift+z) a couple of times. Without this extension you can do this. Unfortunately, with this extension enabled, after you copy(cmd+c), redo does not work. You lose your redo history.

Thanks! Love this extension!

**Comment by stringham** [comment]
Thanks for the report! I didn't realize this behavior was caused by this extension, but it has been bothering me.

I published a fix for this in the marketplace with version `0.1.6`.
