### ISSUE TITLE
not working with latest version of VSCODE

### ISSUE THREAD

**Issue by Bayramito** [stringham/copy-with-imports#8]
Plugin doesnt work with latest version of VSCODE.

**Comment by stringham** [comment]
Can you explain what you mean by "does not work"?

What are the steps to reproduce the issue you're seeing?

**Comment by Bayramito** [comment]
Sorry for responding that late...

Basically it was working great  before but after a copule updates on VSCODE it started to crashed my ESLint.

**How I get this error**

1. Pressing to copy shortcut on File A, (in my case i used command + C in my MAC)
2. and paste with command + V and once i try to save the file the editor stops responding... here is a screenshot from this case.

<img width="1100" alt="Ekran Resmi 2021-03-12 12 41 30" src="https://user-images.githubusercontent.com/44513402/110930024-4a698e80-8331-11eb-96e1-241bdfe10c42.png">

It looks like this and there is not auto imports at the top of the file, I cant even  save the file.
So what i need to is need to press Cancel then reload the editor.

Once i unistalled the copy with imports plugin no crashes on copy/paste anymore

**Comment by stringham** [comment]
I believe this should be fixed now.
